# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 698)
        MainWindow.setMinimumSize(QtCore.QSize(1168, 698))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/h.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(236, 255, 231);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 631, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.batch = QtWidgets.QLabel(self.frame)
        self.batch.setGeometry(QtCore.QRect(10, 10, 611, 521))
        self.batch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.batch.setText("")
        self.batch.setObjectName("batch")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(660, 10, 491, 541))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.information_label = QtWidgets.QLabel(self.frame_2)
        self.information_label.setGeometry(QtCore.QRect(150, 10, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        self.information_label.setFont(font)
        self.information_label.setScaledContents(False)
        self.information_label.setAlignment(QtCore.Qt.AlignCenter)
        self.information_label.setObjectName("information_label")
        self.status_label = QtWidgets.QLabel(self.frame_2)
        self.status_label.setGeometry(QtCore.QRect(30, 460, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.rate_label = QtWidgets.QLabel(self.frame_2)
        self.rate_label.setGeometry(QtCore.QRect(260, 460, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.rate_label.setFont(font)
        self.rate_label.setObjectName("rate_label")
        self.status_value = QtWidgets.QLabel(self.frame_2)
        self.status_value.setGeometry(QtCore.QRect(140, 460, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.status_value.setFont(font)
        self.status_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_value.setObjectName("status_value")
        self.rate_value = QtWidgets.QLabel(self.frame_2)
        self.rate_value.setGeometry(QtCore.QRect(340, 460, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.rate_value.setFont(font)
        self.rate_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rate_value.setObjectName("rate_value")
        self.sample_image = QtWidgets.QLabel(self.frame_2)
        self.sample_image.setGeometry(QtCore.QRect(130, 110, 250, 250))
        self.sample_image.setText("")
        self.sample_image.setObjectName("sample_image")
        self.status_label_2 = QtWidgets.QLabel(self.frame_2)
        self.status_label_2.setGeometry(QtCore.QRect(30, 400, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.status_label_2.setFont(font)
        self.status_label_2.setObjectName("status_label_2")
        self.status_label_3 = QtWidgets.QLabel(self.frame_2)
        self.status_label_3.setGeometry(QtCore.QRect(330, 400, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.status_label_3.setFont(font)
        self.status_label_3.setObjectName("status_label_3")
        self.status_value_2 = QtWidgets.QLabel(self.frame_2)
        self.status_value_2.setGeometry(QtCore.QRect(130, 400, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.status_value_2.setFont(font)
        self.status_value_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_value_2.setObjectName("status_value_2")
        self.status_value_3 = QtWidgets.QLabel(self.frame_2)
        self.status_value_3.setGeometry(QtCore.QRect(410, 400, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.status_value_3.setFont(font)
        self.status_value_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_value_3.setObjectName("status_value_3")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(660, 560, 491, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.current_button = QtWidgets.QPushButton(self.frame_3)
        self.current_button.setGeometry(QtCore.QRect(10, 10, 471, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.current_button.setFont(font)
        self.current_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.current_button.setStyleSheet("\n"
"background-color: rgb(0, 187, 255);")
        self.current_button.setObjectName("current_button")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 550, 631, 31))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.healthy_label = QtWidgets.QLabel(self.frame_4)
        self.healthy_label.setGeometry(QtCore.QRect(170, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.healthy_label.setFont(font)
        self.healthy_label.setStyleSheet("color: rgb(0, 159, 0);")
        self.healthy_label.setObjectName("healthy_label")
        self.spoiled_label = QtWidgets.QLabel(self.frame_4)
        self.spoiled_label.setGeometry(QtCore.QRect(390, 0, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.spoiled_label.setFont(font)
        self.spoiled_label.setStyleSheet("color: rgb(238, 0, 0);")
        self.spoiled_label.setObjectName("spoiled_label")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(134, 0, 31, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(350, 0, 31, 31))
        self.label_2.setObjectName("label_2")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 590, 631, 61))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.prev_back_label = QtWidgets.QLabel(self.frame_5)
        self.prev_back_label.setGeometry(QtCore.QRect(200, 0, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        self.prev_back_label.setFont(font)
        self.prev_back_label.setObjectName("prev_back_label")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(140, 0, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(48)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 111, 61))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1168, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Microgarden"))
        self.information_label.setText(_translate("MainWindow", "Information"))
        self.status_label.setText(_translate("MainWindow", "Status :"))
        self.rate_label.setText(_translate("MainWindow", "Rate :"))
        self.status_value.setText(_translate("MainWindow", "-"))
        self.rate_value.setText(_translate("MainWindow", "-"))
        self.status_label_2.setText(_translate("MainWindow", "Day 0 :"))
        self.status_label_3.setText(_translate("MainWindow", "Day :"))
        self.status_value_2.setText(_translate("MainWindow", "-"))
        self.status_value_3.setText(_translate("MainWindow", "-"))
        self.current_button.setText(_translate("MainWindow", "Current"))
        self.healthy_label.setText(_translate("MainWindow", "HEALTHY"))
        self.spoiled_label.setText(_translate("MainWindow", "SPOILED"))
        #self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/image/h.png\"/></p></body></html>"))
        #self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/image/r.png\"/></p></body></html>"))
        self.prev_back_label.setText(_translate("MainWindow", "see previous"))
        self.label_3.setText(_translate("MainWindow", "<"))
        #self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/image/next.png\"/></p></body></html>"))

#import UI_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

